### ISSUE TITLE
Can't get same result like with other implementations

### ISSUE THREAD

**Issue by sinnlosername** [andreas1327250/argon2-java#1]
Hello!

I'm unable to produce the same result like I do with other argon2 implementations. I tried with argon2 for go and with https://antelle.github.io/argon2-browser/. Both gave me the same result, while you argon2 implementation doesn't. Any idea?

**Comment by andreas1327250** [comment]
problem solved?

**Comment by sinnlosername** [comment]
Yes. Didn't notice it's Argon2i by default. .___.
